language: java
jdk:
- oraclejdk8
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: production
before_deploy:
- openssl aes-256-cbc -K $encrypted_4ad71e6565df_key -iv $encrypted_4ad71e6565df_iv
  -in gae.json.enc -out gae.json -d
