dist: trusty
sudo: false

language: java
jdk:
- oraclejdk8

before_deploy:
- openssl aes-256-cbc -K $encrypted_4ad71e6565df_key -iv $encrypted_4ad71e6565df_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- python3 scripts/replace_vars.py
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: production
