dist: trusty
sudo: false

language: java

jdk:
  - oraclejdk8

before_deploy:
  - tar xvf secrets.tar
  - python3 scripts/replace_vars.py

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: production